kind: pipeline
name: build

steps:
  - name: node-modules
    image: node:12
    commands:
      - (npm ci --only=production)
  - name: deploy
    image: plugins/docker
    settings:
      context: .
      password:
        from_secret: docker_password
      repo: garykim/image-build-autoupdater
      username: garykim
      tags: latest
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/image-build-autoupdater
