kind: pipeline
type: docker
name: build

steps:
  - name: node-modules
    image: node:12
    commands:
      - (npm ci --only=production)
  - name: deploy-edge
    image: plugins/docker
    settings:
      context: .
      password:
        from_secret: docker_password
      repo: garykim/image-build-autoupdater
      username: garykim
      tags:
        - edge
        - latest
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/image-build-autoupdater
  - name: deploy-build
    image: plugins/docker
    settings:
      context: .
      password:
        from_secret: docker_password
      repo: garykim/image-build-autoupdater
      username: garykim
      auto_tag: true
    when:
      branch:
        - master
      event:
        - tag
      repo:
        - gary-kim/image-build-autoupdater
